"""create cases table

Revision ID: 0e67617f9ca4
Revises: 
Create Date: 2026-08-18 12:19:08.820297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e67617f9ca4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_external_id', sa.String(length=100), nullable=False),
    sa.Column('requested_service', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            status IN (\n                'received',\n                'processing',\n                'awaiting_review',\n                'completed',\n                'failed'\n            )\n            ", name='ck_cases_status'),
    sa.CheckConstraint("priority IN ('routine', 'urgent')", name='ck_cases_priority'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_patient_external_id'), 'cases', ['patient_external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_patient_external_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
