"""add case review runs table

Revision ID: 79e83432fb28
Revises: dff5b61936c5
Create Date: 2026-08-19 19:46:12.050088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79e83432fb28'
down_revision: Union[str, Sequence[str], None] = 'dff5b61936c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_review_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='queued', nullable=False),
    sa.Column('document_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=200), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            status IN (\n                'queued',\n                'running',\n                'awaiting_human_review',\n                'completed',\n                'rejected',\n                'failed'\n            )\n            ", name='ck_case_review_runs_status'),
    sa.CheckConstraint('cardinality(document_ids) BETWEEN 1 AND 50', name='ck_case_review_runs_document_count'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temporal_workflow_id', name='uq_case_review_runs_temporal_workflow_id')
    )
    op.create_index(op.f('ix_case_review_runs_case_id'), 'case_review_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_review_runs_status'), 'case_review_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_review_runs_status'), table_name='case_review_runs')
    op.drop_index(op.f('ix_case_review_runs_case_id'), table_name='case_review_runs')
    op.drop_table('case_review_runs')
    # ### end Alembic commands ###
