"""add clinical documents table

Revision ID: a7bf3b07832e
Revises: c3c93f83a994
Create Date: 2026-08-18 17:41:55.725239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7bf3b07832e'
down_revision: Union[str, Sequence[str], None] = 'c3c93f83a994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint(
        "ck_audit_events_event_type",
        "audit_events",
        type_="check",
    )

    op.create_check_constraint(
        "ck_audit_events_event_type",
        "audit_events",
        (
            "event_type IN ("
            "'case_created', "
            "'status_changed', "
            "'ai_review_started', "
            "'ai_review_completed', "
            "'human_review_completed', "
            "'processing_failed', "
            "'document_uploaded'"
            ")"
        ),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name='ck_clinical_documents_positive_size'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'content_sha256', name='uq_clinical_documents_case_hash')
    )
    op.create_index(op.f('ix_clinical_documents_case_id'), 'clinical_documents', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        op.f("ix_clinical_documents_case_id"),
        table_name="clinical_documents",
    )
    op.drop_table("clinical_documents")

    # Add the following after drop_table.
    op.drop_constraint(
        "ck_audit_events_event_type",
        "audit_events",
        type_="check",
    )

    op.create_check_constraint(
        "ck_audit_events_event_type",
        "audit_events",
        (
            "event_type IN ("
            "'case_created', "
            "'status_changed', "
            "'ai_review_started', "
            "'ai_review_completed', "
            "'human_review_completed', "
            "'processing_failed'"
            ")"
        ),
    )