"""add clinical extractions table

Revision ID: bce1889409c0
Revises: a7bf3b07832e
Create Date: 2026-08-18 19:58:57.495070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bce1889409c0'
down_revision: Union[str, Sequence[str], None] = 'a7bf3b07832e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(source_sha256) = 64', name='ck_clinical_extractions_source_sha256'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['clinical_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'provider_name', 'model_name', 'schema_version', name='uq_clinical_extractions_provider_run')
    )
    op.create_index(op.f('ix_clinical_extractions_case_id'), 'clinical_extractions', ['case_id'], unique=False)
    op.create_index(op.f('ix_clinical_extractions_document_id'), 'clinical_extractions', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_extractions_document_id'), table_name='clinical_extractions')
    op.drop_index(op.f('ix_clinical_extractions_case_id'), table_name='clinical_extractions')
    op.drop_table('clinical_extractions')
    # ### end Alembic commands ###
